version: "3.9"
networks:
  deploy-stock-app:
    driver: bridge
services:
  app:
    container_name: stockapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5130:5130"
    networks:
      - deploy-stock-app
    depends_on:
      - mssqldb
    environment:
      - TokenOptions__Token=_
      - ConnectionStrings__Default=_
  mssqldb:
    container_name: stockappdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456@ab
    ports:
      - "8002:1433"
    networks:
      - deploy-stock-app
